import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TodoProvider } from "@/context/Todo";
import { ToastContainer } from 'react-toastify'
import 'react-toastify/dist/ReactToastify.css'
import { getServerSession } from "next-auth";
import SessionProvider from "@/component/SessionProvider";
import { cookies } from "next/headers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Todo | Auth",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {

  
  const session = await getServerSession() // for geting session in serverside compnent 
  const cookie = (await cookies()).getAll() // for cookies review
  // console.log(cookie);
  
  // server component ma direct mogodb connect kre k data ly sakty baghir api likhy just wait k sath db connet kro or schema sy data lelo 


  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased select-none `}
      >
        <SessionProvider session={session} > 

          <TodoProvider>
            {children}
            <ToastContainer
              position="top-center"
              autoClose={1500}
              closeOnClick
              draggable
              pauseOnHover
              theme="light"
            />
          </TodoProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
